# Unbind all keys and set defaut keys
unbind-key -a
source-file ~/.tmux_reset.conf

# Change default prefix key to ctrl + space
unbind C-b
set -g prefix C-Space

# Reload tmux config file on prefix + R
unbind R
bind R source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# Bind prefix + v to split window vertically
unbind v
unbind %
bind v split-window -h
# bind v split-window -h -c "#{pane_current_path}"

# Bind prefix + h to split window horizontally
unbind h
unbind '"'
bind h split-window -v
# bind h split-window -v -c "#{pane_current_path}"

# Bind prefix + vim keybindings for navigating panes
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# command shortcuts
unbind-key -n 1
bind 1 send-keys "ssh srv" Enter
unbind-key -n 2
bind 2 send-keys "ssh vps" Enter
unbind-key -n t
bind t send-keys "htop" Enter
unbind-key -n m
bind m run-shell "
  tmux rename-window 'mntr' && \
  tmux send-keys 'ssh srv' Enter && \
  tmux send-keys 'htop' Enter && \
  tmux split-window -h && \
  tmux send-keys 'ssh vps' Enter && \
  tmux send-keys 'htop' Enter && \
  tmux split-window -v && \
  tmux send-keys 'htop' Enter && \
  tmux select-pane -L && \
  tmux split-window -v && \
  tmux send-keys 'ssh srv' Enter && \
  tmux send-keys 'nvtop' Enter && \
  tmux select-pane -U
"

# Allow longer output history
set -g history-limit 100000

# Refresh window functionality using prefix + r
unbind r
bind r new-window \; kill-window -t !

# Change rename window to prefix + n
unbind n #DEFAULT KEY: Move to next window
bind n command-prompt "rename-window '%%'"

# Change new window key to prefix + w
unbind w #DEFAULT KEY: change current window interactively
bind w new-window -a
# bind w new-window -c "#{pane_current_path}"

# Bind alt + j/k to navigate windows
bind -n M-h previous-window
bind -n M-l next-window

# Use vim keybindings
set -g mode-keys vi

# Use vim keybindings for selection and copying
unbind -T copy-mode-vi Space # Defautl for begin-selection
unbind -T copy-mode-vi Enter # Default for copy-selection
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
# override default "enter" behaviour
bind -T copy-mode-vi C-j send-keys -X cancel \; select-pane -D

# Remove escape delay to prevent conflicting vim and tmux behaviour
set -s escape-time 0

# Allow OSC 52 sequences to pass through tmux
set -g allow-passthrough on
set -g set-clipboard on
# set -as terminal-features ",xterm*:clipboard"

# Settings for visual theme
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'dawn'
set -g status-style "bg=black"
set -g pane-border-style "fg=black"
#set -g pane-border-style "fg=lightgrey"

# Initialise tmux plugin manager (keep at bottom)
run '~/.tmux/plugins/tpm/tpm'
